# Generated by Django 4.2.7 on 2026-08-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_fileaccess_expires_at_osdagfile_sha256_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osdagfile',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
